USE ForumDatabase
GO

ALTER TABLE ForumAppSchema.Users
DROP CONSTRAINT UQ__Users__A9D10534BC88D724;

ALTER TABLE ForumAppSchema.Users
DROP CONSTRAINT UQ__Users__536C85E462550CDD;



ALTER TABLE ForumAppSchema.Users
ALTER COLUMN Email NVARCHAR(50) NOT NULL;

ALTER TABLE ForumAppSchema.Users
ADD CONSTRAINT UQ_Users_Email UNIQUE (Email);


ALTER TABLE ForumAppSchema.Users 
ALTER COlUMN Username NVARCHAR(50) NOT NULL;

ALTER TABLE ForumAppSchema.Users
ADD CONSTRAINT UQ_Users_Username UNIQUE (Username);
